### ISSUE TITLE
Cannot import file in v2.2.0

### ISSUE THREAD

**Issue by JeffreyWardman** [RivinHD/ScriptToButton#21]
**Describe the bug**
Cannot import files.

```
Traceback (most recent call last):
  File "ScriptToButton/operators.py", line 457, in execute
    py_fail = functions.import_py(
  File "ScriptToButton/functions.py", line 653, in import_py
    return import_button(filepath, context, STB_pref, txt)
TypeError: import_button() takes 3 positional arguments but 4 were given
```

**To Reproduce**
1. Click `Import`
2. Select Python file to import
3. See error

**Expected behavior**
Button was imported.

**Version Information:**
 - Add-on Version [ 2.2.0]
 - Blender Version [3.6.2]

**Comment by RivinHD** [comment]
Thanks for the bug report

**Comment by JeffreyWardman** [comment]
No worries at all. Can confirm it works on my side now.
